-------------------------------------------------------------------------------
Test set: com.google.common.cache.CacheBuilderSpec_ESTest
-------------------------------------------------------------------------------
Tests run: 52, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.531 s <<< FAILURE! -- in com.google.common.cache.CacheBuilderSpec_ESTest
com.google.common.cache.CacheBuilderSpec_ESTest.test34 -- Time elapsed: 0.012 s <<< FAILURE!
java.lang.AssertionError: Exception was not thrown in com.google.common.cache.CacheBuilderSpec$IntegerParser but in com.google.common.base.Preconditions.checkArgument(Preconditions.java:220): org.evosuite.runtime.mock.java.lang.MockThrowable: unknown key java.lang.String@0000000010
	at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:111)
	at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:48)
	at com.google.common.cache.CacheBuilderSpec_ESTest.test34(CacheBuilderSpec_ESTest.java:497)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

